### ISSUE TITLE
Hook models are not being downloaded.

### ISSUE THREAD

**Issue by hugalafutro** [dlandon/zoneminder.master-docker#5]
Hi,
I spun a container up with this docker-compose.yml:
```
version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: dlandon/zoneminder.master:latest
        restart: unless-stopped
        ports:
            - 8438:443/tcp
            - 9009:9000/tcp
        network_mode: "bridge"
        privileged: true
        environment:
            - TZ=Europe/London
            - SHMEM=33%
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=1
            - INSTALL_FACE=0
            - INSTALL_TINY_YOLO3=1
            - INSTALL_YOLO3=1
            - INSTALL_TINY_YOLO4=0
            - INSTALL_YOLO4=0
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - ./config:/config:rw
            - /shares/zm:/var/cache/zoneminder:rw
```
While setting up the hooks and testing manually with running `sudo -u www-data /var/lib/zmeventnotification/bin/zm_event_start.sh 11 2` inside the docker it fails with:
```
Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 402, in <module>
    b, l, c = m.detect(image)
  File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/yolo.py", line 63, in detect
    self.populate_class_labels()
  File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/yolo.py", line 27, in populate_class_labels
    f = open(class_file_abs_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/zmeventnotification/models/yolov3/coco.names'
```
`/var/lib/zmeventnotification/models` is a link to `/config/hook/models`, however the models subdirectory does not exist inside the /config/hook directory indicating the models did not download:
```
root@d635b3cedee6:/config/hook# ls -la
total 84
drwxrwxrwx  2 nobody users  4096 Oct  2 22:41 .
drwxrwxr-x 10   1000  1000  4096 Oct  2 22:33 ..
-rwxrwxrwx  1 nobody users 13568 Oct  2 22:37 objectconfig.ini
-rwxrwxrwx  1 nobody users 15085 Oct  2 22:41 objectconfig.ini.default
-rwxrwxrwx  1   1000 users 29908 Aug  9 01:10 zm_detect.py
-rwxrwxrwx  1   1000 users   545 Aug  9 01:10 zm_event_end.sh
-rwxrwxrwx  1   1000 users  1100 Aug  9 01:10 zm_event_start.sh
-rwxrwxrwx  1   1000 users   716 Aug  9 01:10 zm_train_faces.py
```
I have a VM where I previously set up ZM 1.35 + ES manually. After zipping the models from the vm and uploading it to the docker volume the detection now works correctly.

If there is any other info I can supply so as to why the models didn't download let me know.
